### ISSUE TITLE
Page Title

### ISSUE THREAD

**Issue by captaincoo1** [sebastienb/Bootstrap-3-blank-wordpress-theme#8]
The page titles don't seem to render properly unless I change the title in the header.php file from this:

```<title><?php wp_title(); ?></title>```

to this:

```<title><?php wp_title( '|', true, 'right' ); ?></title>```

This is one change I have to make for every site I use this theme on.

**Comment by roccons** [comment]
Or better, you can just delete the <title> tag in header.php, to let add_theme_support( 'title-tag' ); do its work.

**Comment by captaincoo1** [comment]
Yes, that's what I've been doing lately.  Thanks!

**Comment by roccons** [comment]
you're welcome!
